apiVersion: v1
kind: Pod
metadata:
  name: debughost
spec:
  hostPID: true 
  hostNetwork: true  
  containers:
  - image: alpine
    imagePullPolicy: IfNotPresent
    name: debug
    securityContext:
      privileged: true
      capabilities:
        drop:
        - MKNOD
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
        - name: host
          mountPath: /host
  volumes:
    - name: host
      hostPath:
        path: /
        type: Directory
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Never
  securityContext:
    runAsUser: 0
  #serviceAccount: sshpod
  #serviceAccountName: sshpod
  terminationGracePeriodSeconds: 5
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
