apiVersion: v1
kind: Pod
metadata:
  name: ssh-pod
  namespace: balap-cicd
spec:
  hostPID: true 
  hostNetwork: true  
  containers:
  - image: registry.redhat.io/rhel7/support-tools
    env:
      - name: CONTAINER_RUNTIME_ENDPOINT
        value: "unix:///host/var/run/crio/crio.sock"
      - name: IMAGE_SERVICE_ENDPOINT
        value: "unix:///host/var/run/crio/crio.sock"
    imagePullPolicy: IfNotPresent
    name: ssh-pod
    securityContext:
      privileged: true
      capabilities:
        drop:
        - MKNOD
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
        - name: host
          mountPath: /host
  volumes:
    - name: host
      hostPath:
        path: /
        type: Directory
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-797wv
  nodeName: waw5-pos2-app1.it.p4
  nodeSelector:
    kubernetes.io/hostname: waw5-pos2-app1.it.p4
  restartPolicy: Never
  securityContext:
    runAsUser: 0
  serviceAccount: sshpod
  serviceAccountName: sshpod
  terminationGracePeriodSeconds: 5
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
